[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
solc-optimizer = true
solc-optimizer-runs = 99999
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

[profile.default.ir]
enabled = true

[rpc_endpoints]
arbitrum-goerli = "${ARBITRUM_GOERLI_RPC}"

[etherscan]
arbitrum-goerli = { key = "${ARBITRUM_ETHERSCAN_API_KEY}", url = "https://api-goerli.arbiscan.io/api" }